apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: offering-frontend-component
  description: Offering Frontend
  backstage.io/techdocs-ref: 'url:https://github.com/kambisports/backstage-poc-data/blob/main/docs'
  tags:
    - java
spec:
  type: service
  lifecycle: production
  owner: team-rock
  system: offering-distribution
  providesApis:
    - internal-offering-api